In [2]:
!mkdir -p ../checkpoint/medbert2/

In [ ]:
!CUDA_VISIBLE_DEVICES=1 python ./medbert.py

Some weights of the model checkpoint at trueto/medbert-base-chinese were not used when initializing Bert: ['cls.predictions.decoder.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing Bert from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Bert from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Bert were not initialized from the model checkpoint at trueto/medbert-base-chinese and are newly initialized: ['

100%|█████████████████████████████████████| 3111/3111 [1:56:14<00:00,  2.24s/it]
epoch:[1],train loss is:0.485277 

classification_report: 
               precision    recall  f1-score   support

         不标注       0.91      0.88      0.90      2102
          其他       0.77      0.83      0.80       467
          阳性       0.96      0.97      0.96      7219
          阴性       0.93      0.91      0.92      1271

    accuracy                           0.94     11059
   macro avg       0.89      0.90      0.89     11059
weighted avg       0.94      0.94      0.94     11059

confusion_matrix_: 
 [[1855   32  185   30]
 [  12  386   50   19]
 [ 142   49 6983   45]
 [  22   34   55 1160]]
test loss is:0.457135,test acc is:0.938964,f1_score is:0.894422
Some weights of the model checkpoint at trueto/medbert-base-chinese were not used when initializing Bert: ['cls.predictions.decoder.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predicti

100%|█████████████████████████████████████| 3111/3111 [1:55:56<00:00,  2.24s/it]
epoch:[1],train loss is:0.486201 

classification_report: 
               precision    recall  f1-score   support

         不标注       0.91      0.89      0.90      2121
          其他       0.86      0.76      0.81       451
          阳性       0.96      0.97      0.96      7229
          阴性       0.92      0.94      0.93      1258

    accuracy                           0.94     11059
   macro avg       0.91      0.89      0.90     11059
weighted avg       0.94      0.94      0.94     11059

confusion_matrix_: 
 [[1888    9  190   34]
 [  21  345   65   20]
 [ 149   34 7003   43]
 [  19   15   46 1178]]
test loss is:0.455013,test acc is:0.941676,f1_score is:0.900325
Some weights of the model checkpoint at trueto/medbert-base-chinese were not used when initializing Bert: ['cls.predictions.decoder.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predicti

100%|█████████████████████████████████████| 3111/3111 [1:55:47<00:00,  2.23s/it]
epoch:[0],train loss is:0.590895 

classification_report: 
               precision    recall  f1-score   support

         不标注       0.89      0.85      0.87      2086
          其他       0.77      0.71      0.74       495
          阳性       0.94      0.96      0.95      7162
          阴性       0.90      0.90      0.90      1316

    accuracy                           0.92     11059
   macro avg       0.88      0.86      0.87     11059
weighted avg       0.92      0.92      0.92     11059

confusion_matrix_: 
 [[1774   23  261   28]
 [  23  353   83   36]
 [ 168   45 6886   63]
 [  29   39   62 1186]]
test loss is:0.484643,test acc is:0.922235,f1_score is:0.865984
100%|█████████████████████████████████████| 3111/3111 [1:55:47<00:00,  2.23s/it]
epoch:[1],train loss is:0.485528 

classification_report: 
               precision    recall  f1-score   support

         不标注       0.90      0.88      0.89      2

100%|█████████████████████████████████████| 3111/3111 [1:55:37<00:00,  2.23s/it]
epoch:[0],train loss is:0.592558 

classification_report: 
               precision    recall  f1-score   support

         不标注       0.90      0.85      0.88      2109
          其他       0.81      0.70      0.75       486
          阳性       0.95      0.97      0.96      7192
          阴性       0.89      0.94      0.91      1272

    accuracy                           0.93     11059
   macro avg       0.89      0.86      0.87     11059
weighted avg       0.93      0.93      0.93     11059

confusion_matrix_: 
 [[1802   24  238   45]
 [  19  338   81   48]
 [ 160   36 6943   53]
 [  20   20   42 1190]]
test loss is:0.477063,test acc is:0.928927,f1_score is:0.873792
100%|█████████████████████████████████████| 3111/3111 [1:55:48<00:00,  2.23s/it]
epoch:[1],train loss is:0.485663 

classification_report: 
               precision    recall  f1-score   support

         不标注       0.92      0.89      0.90      2

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
100%|█████████████████████████████████████| 3111/3111 [1:55:44<00:00,  2.23s/it]
epoch:[0],train loss is:0.592386 

classification_report: 
               precision    recall  f1-score   support

         不标注       0.88      0.85      0.87      2105
          其他       0.76      0.72      0.74       442
          阳性       0.95      0.96      0.96      7173
          阴性       0.91      0.92      0.92      1339

    accuracy                           0.93     11059
   macro avg       0.88      0.86      0.87     11059
weighted avg       0.92      0.93      0.92     11059

confusion_matrix_: 
 [[1795   21  248   41]
 [  31  319   61   31]
 [ 188   51 6884   50]
 [  29   27   47 1236]]
te

100%|█████████████████████████████████████| 3111/3111 [1:54:07<00:00,  2.20s/it]
epoch:[1],train loss is:0.485351 

classification_report: 
               precision    recall  f1-score   support

         不标注       0.90      0.88      0.89      2105
          其他       0.82      0.77      0.80       442
          阳性       0.96      0.97      0.96      7173
          阴性       0.92      0.94      0.93      1339

    accuracy                           0.94     11059
   macro avg       0.90      0.89      0.89     11059
weighted avg       0.94      0.94      0.94     11059

confusion_matrix_: 
 [[1859   18  192   36]
 [  30  340   49   23]
 [ 153   39 6927   54]
 [  25   16   45 1253]]
test loss is:0.460727,test acc is:0.938512,f1_score is:0.893988
Some weights of the model checkpoint at trueto/medbert-base-chinese were not used when initializing Bert: ['cls.predictions.decoder.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predicti

100%|█████████████████████████████████████| 3111/3111 [1:54:40<00:00,  2.21s/it]
epoch:[1],train loss is:0.486099 

classification_report: 
               precision    recall  f1-score   support

         不标注       0.92      0.88      0.90      2086
          其他       0.82      0.77      0.79       445
          阳性       0.96      0.97      0.96      7226
          阴性       0.92      0.94      0.93      1302

    accuracy                           0.94     11059
   macro avg       0.90      0.89      0.90     11059
weighted avg       0.94      0.94      0.94     11059

confusion_matrix_: 
 [[1830   15  209   32]
 [  13  344   56   32]
 [ 139   31 7011   45]
 [  14   31   38 1219]]
test loss is:0.457193,test acc is:0.940772,f1_score is:0.895612
Some weights of the model checkpoint at trueto/medbert-base-chinese were not used when initializing Bert: ['cls.predictions.decoder.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predicti

  2%|▊                                      | 67/3111 [02:30<1:53:44,  2.24s/it]